title: EIC Canada
description: Coordinating Canadian Participation in the Electron Ion Collider
github_username: eic-canada

plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-titles-from-headings

header_pages: 
 - management.md
 - leadership.md
 - members.md
 - codeofconduct.md
 - documents.md

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

google_analytics: G-9HZLR8YNTC

theme: minima
