title: EIC Canada
description: Canadian Participation in the Electron Ion Collider
github_username: eic-canada

plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-titles-from-headings

theme: jekyll-theme-minimal
